name: .NET5.0 Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build --no-self-contained --configuration Release
    - name: Pack
      run: |
        mv ./bin/Release/net5.0/publish/ ./wgconfig/
        rm -f ./wgconfig/wgconfig
        rm -f ./wgconfig/*.deps.json
        rm -f ./wgconfig/*.pdb
        zip -r release.zip ./wgconfig/
        
